import express from 'express'; import cors from 'cors'; import {db} from './db.js';
const app=express(); const port=Number(process.env.PORT??4000); app.use(cors()); app.use(express.json({limit:'100kb'}));
const now=()=>new Date().toISOString();
app.get('/api/v1/health',(_,r)=>r.json({ok:true,time:now()}));
app.post('/api/v1/ingest',(req,res)=>{const b=req.body;if(!b.deviceId||!b.userId||!b.startedAt||!b.endedAt||typeof b.durationSeconds!=='number'||!b.state)return res.status(400).json({message:'Invalid activity payload'});const n=now();const tx=db.transaction(()=>{db.prepare(`INSERT INTO devices(device_id,user_id,last_seen_at,created_at) VALUES(?,?,?,?) ON CONFLICT(device_id) DO UPDATE SET user_id=excluded.user_id,last_seen_at=excluded.last_seen_at`).run(b.deviceId,b.userId,n,n);db.prepare(`INSERT INTO activity_events(device_id,user_id,event_type,started_at,ended_at,duration_seconds,application,window_title,state,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(b.deviceId,b.userId,b.eventType??'activity',b.startedAt,b.endedAt,Math.max(0,Math.round(b.durationSeconds)),b.application??null,b.windowTitle??null,b.state,n)});tx();res.status(202).json({accepted:true})});
app.get('/api/v1/dashboard/summary',(_,res)=>{const devices=db.prepare('SELECT COUNT(*) count FROM devices').get() as any;const active=db.prepare("SELECT COALESCE(SUM(duration_seconds),0) seconds FROM activity_events WHERE state='active'").get() as any;const idle=db.prepare("SELECT COALESCE(SUM(duration_seconds),0) seconds FROM activity_events WHERE state='idle'").get() as any;const live=db.prepare("SELECT COUNT(*) count FROM devices WHERE last_seen_at>=datetime('now','-2 minutes')").get() as any;res.json({devices:devices.count,activeDevices:live.count,activeSeconds:active.seconds,idleSeconds:idle.seconds})});
app.get('/api/v1/dashboard/applications',(_,res)=>res.json(db.prepare(`SELECT COALESCE(application,'Unknown') application,SUM(duration_seconds) seconds,COUNT(*) events FROM activity_events WHERE state='active' GROUP BY application ORDER BY seconds DESC LIMIT 10`).all()));
app.get('/api/v1/dashboard/recent',(_,res)=>res.json(db.prepare(`SELECT id,device_id deviceId,user_id userId,started_at startedAt,ended_at endedAt,duration_seconds durationSeconds,application,window_title windowTitle,state FROM activity_events ORDER BY id DESC LIMIT 30`).all()));
app.listen(port,()=>console.log(`API: http://localhost:${port}`));
